"""
Ed25519 signing for agent run records.

Key hierarchy (in priority order):
  1. TRUSTLAYER_SIGNING_KEY_PEM env var  — PEM-encoded Ed25519 private key
  2. ~/.provn/signing_key.pem            — auto-generated on first use via `trustlayer keygen`
  3. HMAC-SHA256 fallback                — uses the API key; tamper-evident, not asymmetrically verifiable

Public verification:
  Anyone with the public key (embedded in the Agent Passport) can verify any run signature
  using `trustlayer verify <run_id>` or the /verify/<run_id> API endpoint — no API key needed.

Generate a keypair:
  trustlayer keygen
  # Creates ~/.provn/signing_key.pem and ~/.provn/signing_key.pub.pem
  # Set TRUSTLAYER_SIGNING_KEY_PEM=$(cat ~/.provn/signing_key.pem)
"""
import hashlib
import hmac
import json
import os
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

_DEFAULT_KEY_DIR  = Path.home() / ".provn"
_DEFAULT_KEY_PATH = _DEFAULT_KEY_DIR / "signing_key.pem"
_DEFAULT_PUB_PATH = _DEFAULT_KEY_DIR / "signing_key.pub.pem"


def generate_keypair(output_dir: Optional[str] = None) -> Tuple[str, str]:
    """
    Generate an Ed25519 keypair and save to disk.

    Args:
        output_dir: Directory to save keys (default: ~/.provn/)

    Returns:
        (private_key_pem, public_key_pem) as strings.
    """
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives.serialization import (
        Encoding, NoEncryption, PrivateFormat, PublicFormat,
    )

    key_dir = Path(output_dir) if output_dir else _DEFAULT_KEY_DIR
    key_dir.mkdir(parents=True, exist_ok=True)

    private_key = Ed25519PrivateKey.generate()
    public_key  = private_key.public_key()

    priv_pem = private_key.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, NoEncryption()).decode()
    pub_pem  = public_key.public_bytes(Encoding.PEM, PublicFormat.SubjectPublicKeyInfo).decode()

    (key_dir / "signing_key.pem").write_text(priv_pem)
    (key_dir / "signing_key.pub.pem").write_text(pub_pem)

    return priv_pem, pub_pem


def _load_private_key_pem() -> Optional[str]:
    """Load private key PEM from env var or default file location."""
    pem = os.environ.get("TRUSTLAYER_SIGNING_KEY_PEM", "")
    if pem:
        return pem
    if _DEFAULT_KEY_PATH.exists():
        return _DEFAULT_KEY_PATH.read_text()
    return None


def get_public_key_pem() -> Optional[str]:
    """Return the public key PEM for embedding in passports / verification endpoints."""
    pub_pem = os.environ.get("TRUSTLAYER_VERIFY_KEY_PEM", "")
    if pub_pem:
        return pub_pem
    if _DEFAULT_PUB_PATH.exists():
        return _DEFAULT_PUB_PATH.read_text()
    return None


def _stable_json(data: Dict[str, Any]) -> bytes:
    """Produce deterministic JSON bytes for signing."""
    return json.dumps(data, sort_keys=True, separators=(",", ":"), default=str).encode()


def sign_run(run_dict: Dict[str, Any], secret_key: Optional[str] = None) -> str:
    """
    Sign a run record. Returns a hex string signature.

    Signing priority:
      1. Ed25519 via TRUSTLAYER_SIGNING_KEY_PEM env var (preferred — public-key verifiable)
      2. Ed25519 via ~/.provn/signing_key.pem (auto-generated by `trustlayer keygen`)
      3. HMAC-SHA256 fallback using the API key (tamper-evident, requires API key to verify)

    The signature format is "<algo>:<hex>":
      ed25519:abc123...   — publicly verifiable, no API key needed
      hmac-sha256:def456... — requires API key to verify
    """
    payload = {k: v for k, v in run_dict.items() if k != "signature"}
    payload_bytes = _stable_json(payload)

    try:
        from cryptography.hazmat.primitives.serialization import load_pem_private_key
        pem_str = _load_private_key_pem()
        if pem_str:
            private_key = load_pem_private_key(pem_str.encode(), password=None)
            sig_bytes = private_key.sign(payload_bytes)
            return f"ed25519:{sig_bytes.hex()}"
    except Exception:
        pass

    # HMAC fallback
    key = (secret_key or os.environ.get("TRUSTLAYER_API_KEY", "dev-secret")).encode()
    sig = hmac.new(key, payload_bytes, hashlib.sha256).hexdigest()
    return f"hmac-sha256:{sig}"


def verify_run(
    run_dict: Dict[str, Any],
    signature: str,
    secret_key: Optional[str] = None,
    public_key_pem: Optional[str] = None,
) -> bool:
    """
    Verify a run signature.

    Args:
        run_dict: The run record dict (without the signature field).
        signature: The signature string (e.g. "ed25519:abc123..." or "hmac-sha256:...").
        secret_key: API key for HMAC verification (only needed for hmac-sha256 sigs).
        public_key_pem: PEM-encoded Ed25519 public key (only needed for ed25519 sigs).
                        If not supplied, reads from env/disk automatically.

    Returns:
        True if the signature is valid.
    """
    payload = {k: v for k, v in run_dict.items() if k != "signature"}
    payload_bytes = _stable_json(payload)

    if signature.startswith("ed25519:"):
        try:
            from cryptography.hazmat.primitives.serialization import load_pem_public_key
            sig_bytes = bytes.fromhex(signature.removeprefix("ed25519:"))
            pem_str = public_key_pem or get_public_key_pem()
            if pem_str:
                pub_key = load_pem_public_key(pem_str.encode())
                pub_key.verify(sig_bytes, payload_bytes)
                return True
        except Exception:
            return False

    if signature.startswith("hmac-sha256:"):
        key = (secret_key or os.environ.get("TRUSTLAYER_API_KEY", "dev-secret")).encode()
        expected = hmac.new(key, payload_bytes, hashlib.sha256).hexdigest()
        provided = signature.removeprefix("hmac-sha256:")
        return hmac.compare_digest(expected, provided)

    return False


def action_hash(run_dict: Dict[str, Any]) -> str:
    """SHA-256 hash of the run payload for quick identity checks."""
    payload = {k: v for k, v in run_dict.items() if k != "signature"}
    return hashlib.sha256(_stable_json(payload)).hexdigest()[:16] + "..."
